<?php

namespace Container0eESUTo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3PBdZsQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3PBdZsQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3PBdZsQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'personnalite' => ['privates', '.errored..service_locator.3PBdZsQ.App\\Entity\\Personnalite', NULL, 'Cannot autowire service ".service_locator.3PBdZsQ": it needs an instance of "App\\Entity\\Personnalite" but this type has been excluded in "config/services.yaml".'],
        ], [
            'personnalite' => 'App\\Entity\\Personnalite',
        ]);
    }
}
