<?php

namespace Container0eESUTo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPersonnaliteControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\PersonnaliteController' shared autowired service.
     *
     * @return \App\Controller\PersonnaliteController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/PersonnaliteController.php';

        $container->services['App\\Controller\\PersonnaliteController'] = $instance = new \App\Controller\PersonnaliteController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['App\\Repository\\PersonnaliteRepository'] ?? $container->load('getPersonnaliteRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.oYvDZU_'] ?? $container->load('get_ServiceLocator_OYvDZUService'))->withContext('App\\Controller\\PersonnaliteController', $container));

        return $instance;
    }
}
