<?php

namespace ContainerVEDL1to;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPersonnaliteService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.3PBdZsQ.App\Entity\Personnalite' shared service.
     *
     * @return \App\Entity\Personnalite
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.3PBdZsQ": it needs an instance of "App\\Entity\\Personnalite" but this type has been excluded in "config/services.yaml".');
    }
}
