<?php

namespace ContainerVEDL1to;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUx_LiveComponent_EventListener_DataModelPropsSubscriberService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'ux.live_component.event_listener.data_model_props_subscriber' shared service.
     *
     * @return \Symfony\UX\LiveComponent\EventListener\DataModelPropsSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/src/EventListener/DataModelPropsSubscriber.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-twig-component/src/ComponentStack.php';

        return $container->privates['ux.live_component.event_listener.data_model_props_subscriber'] = new \Symfony\UX\LiveComponent\EventListener\DataModelPropsSubscriber(($container->privates['ux.twig_component.component_stack'] ??= new \Symfony\UX\TwigComponent\ComponentStack()), ($container->privates['property_accessor'] ?? $container->load('getPropertyAccessorService')));
    }
}
