<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVEDL1to\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVEDL1to/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerVEDL1to.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerVEDL1to\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerVEDL1to\App_KernelTestDebugContainer([
    'container.build_hash' => 'VEDL1to',
    'container.build_id' => '653fc984',
    'container.build_time' => 1684515887,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVEDL1to');
