<?php

namespace ContainerCAUbK8B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHtmlSanitizer_Config_DefaultService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'html_sanitizer.config.default' shared service.
     *
     * @return \Symfony\Component\HtmlSanitizer\HtmlSanitizerConfig
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/html-sanitizer/HtmlSanitizerConfig.php';

        $instance = new \Symfony\Component\HtmlSanitizer\HtmlSanitizerConfig();

        $instance = $instance->allowSafeElements();
        $instance = $instance->forceHttpsUrls(false);
        $instance = $instance->allowLinkHosts(NULL);
        $instance = $instance->allowRelativeLinks(false);
        $instance = $instance->allowMediaHosts(NULL);
        $container->privates['html_sanitizer.config.default'] = $instance = $instance->allowRelativeMedias(false);

        return $instance;
    }
}
